card_image: ''
created_at: 2025-03-24 20:28:58.336421
creator_id: unknown
deployment:
  last_deployed: null
  type: null
  url: ''
description: Nextjs App with Clerk auth and Airtable store
domain: ''
features:
- ''
getting_started_screen: false
getting_started_screen_index: 0
git:
  branch: main
  remote: origin
  url: 'https://github.com/memextech/nextjs_clerk_airtable'
hero_image: ''
icon: ''
is_published: false
pills:
- icon: ''
  label: ''
  prompt: ''
project_id: ''
published_at: null
requirements:
- description: ''
  type: ''
slug: ''
storage:
  compression_enabled: null
  gcs_path: null
  last_sync: null
  max_file_size_mb: null
  size_bytes: null
title: Nextjs App with Clerk auth and Airtable store
tools:
- name: ''
  role: ''
  type: ''
  version: ''
updated_at: 2025-03-24 20:28:58.336454
